export const ARTICLE_PROVIDER_PROVIDER = Symbol('ARTICLE_PROVIDER_PROVIDER');
export const CREATE_ARTICLE_USE_CASE_PROVIDER = Symbol(
  'CREATE_ARTICLE_USE_CASE_PROVIDER'
);
export const UPDATE_ARTICLE_USE_CASE_PROVIDER = Symbol(
  'UPDATE_ARTICLE_USE_CASE_PROVIDER'
);
