export const UNIT_OF_WORK_PROVIDER = Symbol('UNIT_OF_WORK_PROVIDER');
export const CREATE_ARTICLE_USE_CASE_PROVIDER = Symbol(
  'CREATE_ARTICLE_USE_CASE_PROVIDER'
);
export const UPDATE_ARTICLE_USE_CASE_PROVIDER = Symbol(
  'UPDATE_ARTICLE_USE_CASE_PROVIDER'
);
