name: Check Pull Request

on:
  pull_request:
    branches:
      - develop
      - release

permissions:
  contents: read

jobs:
  check-pull-request-validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.18.0'
          cache: 'npm'

      - run: npm ci

      - run: npm audit --audit-level=high

      - run: npx nx run-many -t test
