name: Publish

concurrency: production

on:
  push:
    branches:
      - release
      - STACKS-17

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.18.0'
          cache: 'npm'

      - run: npm ci

      - run: npx nx run-many -t build

      - run: node scripts/update-dependencies-versions.js

      - run: npx nx run-many -t nx-release-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
